### ISSUE TITLE
Force Dark Mode macOS

### ISSUE THREAD

**Issue by andrewcincotta** [TetsuakiBaba/quickGPT#1] opened 2024-02-20 19:22 UTC
How can I force dark mode all the time on macOS?
Currently on the latest version of macOS and quickGPT.

**Comment by TetsuakiBaba** [comment] 2024-02-21 20:07
@andrewcincotta quickGPT follows macOS appearance mode, so if you are using macOS in dark mode then quickGPT will also be in dark mode. I am on sonoma 14.2.1 and have confirmed that it will be in dark mode.

In other words, if you always use macOS in dark mode, quickGPT will always be in dark mode. If you want to force quickGPT to be in dark mode even if macOS is in light mode, this is not possible at this time. However, I think your request would be beneficial to our users and I will update the application with the feature soon. Thanks!

<img width="1116" alt="スクリーンショット 2024-02-22 5 06 48" src="https://github.com/TetsuakiBaba/quickGPT/assets/1846131/c044cbc0-5780-4193-8861-c762100c9288">

**Comment by andrewcincotta** [comment] 2024-02-21 21:52
> @andrewcincotta quickGPT follows macOS appearance mode, so if you are using macOS in dark mode then quickGPT will also be in dark mode. I am on sonoma 14.2.1 and have confirmed that it will be in dark mode.
> 
> In other words, if you always use macOS in dark mode, quickGPT will always be in dark mode. If you want to force quickGPT to be in dark mode even if macOS is in light mode, this is not possible at this time. However, I think your request would be beneficial to our users and I will update the application with the feature soon. Thanks!
> 
> <img alt="スクリーンショット 2024-02-22 5 06 48" width="1116" src="https://private-user-images.githubusercontent.com/1846131/306760057-c044cbc0-5780-4193-8861-c762100c9288.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NTI1ODcsIm5iZiI6MTcwODU1MjI4NywicGF0aCI6Ii8xODQ2MTMxLzMwNjc2MDA1Ny1jMDQ0Y2JjMC01NzgwLTQxOTMtODg2MS1jNzYyMTAwYzkyODgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjFUMjE1MTI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjgxNmYxNmFhOWE4N2I3YzU4NWM1ZmY2MDQwOWI5ZDM3NGQ1MThmM2ZkZmUyYmMyNDRlNjRjYzlmYmViMGEzNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7hefYoYreoZmCUKivTfNly3NJIAfsfRHSvzutH1uHaI">

My app works in the same fashion, do you know how to override this?

**Comment by TetsuakiBaba** [comment] 2024-02-21 23:15
@andrewcincotta hi, there is no way to set force to be dark mode on the user side. but if you are developer, just put one line of code, nativeTheme.themeSource = 'dark'; anywhere in the main.js

**Comment by andrewcincotta** [comment] 2024-02-21 23:16
Thanks! That saved me a lot of time in debugging!

**Closed as completed** 2024-02-21 23:16 UTC

**Comment by TetsuakiBaba** [comment] 2024-02-22 00:05
@andrewcincotta 
I have just released the latest version (v1.1.4) of quickGPT. This release includes the function to select a theme. Please use this one; since you are already using quickGPT, you may have already been notified of the update.
